version: 0.2

phases:
  install:
    commands:
      - echo installing nginx
      - echo sudo apt-get update
      - echo sudo apt-get install nginx-y
  build:
    commands:
      - echo build started on 'date'
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - /var/www/html/index.html
